### ISSUE TITLE
streamlit run cheapBuy_user_interface.py command not working

### ISSUE THREAD

**Issue by mahathii** [csc510fall23g45/cheapBuy#14]

**Comment by sairajzero** [comment]
There are 2 files: cheapBuy_user_interface.py and cheapBuy_user_interface1.py

**Comment by sairajzero** [comment]
Updated the run file. [59d852c](https://github.com/csc510fall23g45/cheapBuy/commit/59d852cc003cd2f25be7c581c6738d58ce7085d8)
